language: node_js
node_js:
- 5.1.0
branches:
  only:
  - master
  - deploy
script: npm run build:prod
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: ZHQTMGdm+QzgaFVuVhPjUaf/xFgNy+BoopwdmZeT3NwH6GSJQ7I2NsUHsPRGOHSoeX+Iblqa6CR9XRj0BmT6Kmd5mg32h5hG37NUXKBBS1r9g1AwkwEx0O+P01BVJqeDlEbm9L9qKHpdxgdp1u+2IZvkEt0QHtW3E8iHQNcnaBbLWJTLPQDkzj1Aoy21rn+8BgAa6E238loiBbQfJMLqUkBDwKeaEoSXFyvy24AQwnnEWixoyHlzPE2JmtWaFnku81WV/ThnUPkQENYaXREj4fsuGREoLgqGtFAnYoOp5k5Zbkcy+qXiMlq0xWM5usyERnR9Vy8JJUlMxS8+3FYkleULbySRrbBSH6vULW+uBldhhdNxfee9vXLz1wREadW8fxJuiC0lWdZr5thzu2bMzirzw8lbbX7zFt1vHpNjTSLjaUozAz+BOLa+W6r8z3xUGLefqRKbPVaEG8GiUpGDkYlWLIQWOyVm60tsItw6EuvjUE0fXVT3IXgk2REMLtqLIJy5U7y5F5gNjd5k3ba6hjpSvlVoZJLMA8afsX8ctCCzuKSqzcw3c76/I1xoXZeLgLNmWUPRfKY7I+uSiwXb8kj1j89trM9EbROCFAfk/0yD/7SVQaK3lw18PqFwbqJS8t3RyaQmc/a3BfMZM2me4yd2sPk3y/HIZnwcG/w3MY0=
  run:
  - npm i -g http-server
  - npm run start
  on:
    branch: deploy
